[build]
    functions = "netlify/functions"
    command = "bundle exec jekyll build"
    publish = "_site"

[build.processing]
    skip_processing = false

[build.processing.html]
    pretty_urls = true

[build.processing.images]
    compress = true

[build.processing.css]
    bundle = true
    minify = true

[build.processing.js]
    bundle = true
    minify = true

[[plugins]]
    package = "@netlify/plugin-functions-install-core"

[[plugins]]
    package = "@netlify/plugin-lighthouse"